services:
  mongodb:
    image: mongo:latest
    container_name: graphql
    environment:
      MONGO_INITDB_ROOT_USERNAME: graphql
      MONGO_INITDB_ROOT_PASSWORD: graphql
      MONGO_INITDB_DATABASE: graphql
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
    driver: local
